name: Automatic upload to Google Cloud Storage

on:
  push:
    branches:
    - main

jobs:
  build:
    - name: Checkout
      uses: actions/checkout@v2
    - name: upload file
      # runs-on: ubuntu-latest 
      steps:
        - id: upload-file
          uses: google-github-actions/upload-cloud-storage@main
          with:
            credentials: ${{ secrets.gcp_credentials }}
            destination: demo-2021
