name: Build and Deploy to Google Cloud Storage

on:
  push:
    branches:
    - main

jobs:
  setup-build-deploy:
    name: Setup and Upload
    runs-on: ubuntu-latest

    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
    
    - name: upload-file
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: ../update-storage-by-github-action/
        destination: demo-2021
