name: Automatic upload to Google Cloud Storage

on:
  push:
    branches:
    - main

jobs:
  steps:
    - id: upload-file
      uses: google-github-actions/upload-cloud-storage@main
      with:
        credentials: ${{ secrets.gcp_credentials }}
        path: ./
        destination: demo-2021
