name: Build and Deploy to Google Cloud Storage

on:
  push:
    branches:
    - main

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
    
    - id: upload-file
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: .
        # path: ../update-storage-by-github-action/
        destination: demo-2021



    # - name: Setup - gcloud / gsutil
    #   uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    #   with:
    #       path: ./update-storage-by-github-action
    #       destination: demo-2021



# jobs:
#   build:
#     - name: Checkout
#       uses: actions/checkout@v2
#     - name: upload file
#       # runs-on: ubuntu-latest 
#       steps:
#         - id: upload-file
#           uses: google-github-actions/upload-cloud-storage@main
#           with:
#             credentials: ${{ secrets.gcp_credentials }}
#             destination: demo-2021
