# name: Build and Deploy to Google Cloud Storage

# on:
#   push:
#     branches:
#     - main

# jobs:
#   setup-build-deploy:
#     name: Setup and Upload
#     runs-on: ubuntu-latest
#     strategy:
#       max-parallel: 4
#       matrix:
#         python-version: [3.7]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python ${{ matrix.python-version }}
#       uses: actions/setup-python@v1
#       with:
#         python-version: ${{ matrix.python-version }}

    
#     # 建立環境
#     - name: Install Dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r ./requirements.txt

#     # Upload Folder
#     - name: Run Upload
#       env:
#         GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
#       run: |
#         python3 main.py

name: Build and Deploy to Google Cloud Storage

on:
  push:
    branches:
    - main

jobs:
  setup-build-deploy:
    name: Setup and Upload
    runs-on: ubuntu-latest

    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
    
    - id: upload-file
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: ../update-storage-by-github-action/
        destination: demo-2021
