name: Automatic upload to Google Cloud Storage

on:
  push:
    branches:
    - main

steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: upload file
    uses: google-github-actions/upload-cloud-storage@main
    with:
      credentials: ${{ secrets.gcp_credentials }}
      destination: demo-2021

# jobs:
#   build:
#     - name: Checkout
#       uses: actions/checkout@v2
#     - name: upload file
#       # runs-on: ubuntu-latest 
#       steps:
#         - id: upload-file
#           uses: google-github-actions/upload-cloud-storage@main
#           with:
#             credentials: ${{ secrets.gcp_credentials }}
#             destination: demo-2021
