name: Automatic upload to Google Cloud Storage

on:
  push:
    branches:
    - main

jobs:
  build:
    name: upload file
    runs-on: ubuntu-latest 
    steps:
      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: /hsuanchi/update-storage-by-github-action/
          destination: demo-2021
